### ISSUE TITLE
How to use eslint-plugin-pug in eslint flat

### ISSUE THREAD

**Issue by yanzhangshuai** [rashfael/eslint-plugin-vue-pug#29]
How to use eslint-plugin-pug in eslint flat. I use pug and eslint@9 in my vue project. There is a problem that that trouble me.

ts/consistent-type-imports rule will InstanceType<typeof Component> covert to import type Component from 'xxxxxx', but this is error

I need help. Thanks.
![367491052-9822386a-4722-4fae-a401-b7de3d938790](https://github.com/user-attachments/assets/c635b4f1-4b55-4b02-aeae-f2001cf15335)

**Comment by lehni** [comment]
We can't see the error, the images appears to be broken. Could you post the content again?

**Comment by yanzhangshuai** [comment]
> We can't see the error, the images appears to be broken. Could you post the content again?
> 
> But there's a PR for this already, see #26

Sorry, I re-uploaded the image.   

[#26](https://github.com/rashfael/eslint-plugin-vue-pug/pull/26) is open state. And I also made my demands there.

**Comment by someonewithpc** [comment]
Use this in your `eslint.config.js`

```
import { FlatCompat } from '@eslint/eslintrc';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const compat = new FlatCompat({ baseDirectory: __dirname });

export default [
  // Eslint.configs.recommended,
  // ...Vue.configs['flat/recommended'],
  ...compat.extends('plugin:vue-pug/vue3-recommended'),
];
```

**Comment by ziazon** [comment]
> Use this in your `eslint.config.js`
> 
> ```
> import { FlatCompat } from '@eslint/eslintrc';
> import { dirname } from 'node:path';
> import { fileURLToPath } from 'node:url';
> 
> const __filename = fileURLToPath(import.meta.url); // I think these two are only needed for Vite based projects
> const __dirname = dirname(__filename);
> const compat = new FlatCompat({ baseDirectory: __dirname });
> 
> export default [
>   // Eslint.configs.recommended,
>   // ...Vue.configs['flat/recommended'],
>   ...compat.extends('plugin:vue-pug/vue3-recommended'),
> ];
> ```

This works! thank you!

**Comment by glutaminefree** [comment]
Any hope for native support of flat config?

**Comment by tpuida** [comment]
+1

**Comment by leezng** [comment]
Any new progress?

**Comment by rashfael** [comment]
I just released a new major version that adds flat configs just like `eslint-plugin-vue`.

You can try it out by installing `eslint-plugin-vue-pug@flat` and adding the following to your flat config:

```js
…
import pluginVuePug from 'eslint-plugin-vue-pug'

…
  ...pluginVue.configs['flat/recommended'],
  ...pluginVuePug.configs['flat/recommended'],
```

Please try it out, let me know if it works for you and thanks for your patience!

**Comment by tbontb-iaq** [comment]
Can you add Typescript type definitions?

**Comment by rashfael** [comment]
> Can you add Typescript type definitions?
I'll have a look at how that works.

**Comment by Shinigami92** [comment]
> > Can you add Typescript type definitions?
> 
> I'll have a look at how that works.

Summon me and I can help if you wish

**Comment by Shinigami92** [comment]
> [@Shinigami92](https://github.com/Shinigami92?rgh-link-date=2025-03-25T19%3A15%3A37.000Z) It looks like `eslint-plugin-vue` isn't doing much I can copy. Am I missing something big apart from [vuejs/eslint-plugin-vue@`d385140`/lib/index.d.ts](https://github.com/vuejs/eslint-plugin-vue/blob/d38514020768cb1ea21f577f164cc3b82bcf78c9/lib/index.d.ts) ? I can add that easily. Are rule settings something that can be typed or what would be the expectation here? Thanks for your help!

Yes, there is a very new feature and `eslint` now ships freshly with `defineConfig`. Even I would need to look into it 🙂

**Comment by lehni** [comment]
@rashfael could you please consider merging #30? I am still facing the same issue with v1.0.0-alpha.2 and eslint v9.
Merging #30 would fix that.

Also, I cannot find the flat branch that as released as v1.0.0. Is it not on Github?

**Comment by lehni** [comment]
@rashfael thanks for taking care of it!

**Comment by la-magra** [comment]
Has anybody reached this error?

```
$ yarn eslint packages

Oops! Something went wrong! :(

ESLint: 10.2.1

TypeError: Cannot destructure property 'toRegExp' of 'require(...).default' as it is undefined.
    at Object.<anonymous> (.../node_modules/eslint-plugin-vue-pug/lib/rules/component-name-in-template-casing.js:9:9)
    at Module._compile (node:internal/modules/cjs/loader:1830:14)
    at Object..js (node:internal/modules/cjs/loader:1961:10)
    at Module.load (node:internal/modules/cjs/loader:1553:32)
    at Module._load (node:internal/modules/cjs/loader:1355:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.require (node:internal/modules/cjs/loader:1576:12)
    at require (node:internal/modules/helpers:153:16)
    at Object.<anonymous> (.../node_modules/eslint-plugin-vue-pug/lib/index.js:34:42)
    at Module._compile (node:internal/modules/cjs/loader:1830:14)

```
with the following packages:
```
"eslint": "^10.2.1",
"eslint-plugin-vue": "^10.9.0",
"eslint-plugin-vue-pug": "^1.0.0-alpha.5",

```
and this eslint config
```js
// eslint.config.mjs
import vuePugPlugin from 'eslint-plugin-vue-pug'
import vuePlugin from 'eslint-plugin-vue'
import {defineConfig} from 'eslint/config'

export default defineConfig([
  [
    {
      files: ['**/*.vue'],
      extends: [
        ...vuePlugin.configs['flat/recommended'],
        ...vuePugPlugin.configs['flat/recommended'],
      ]
    },
  ]
])
```

I fixed it by editing `node_modules/eslint-plugin-vue-pug/lib/rules/component-name-in-template-casing.js:9`
```diff
- const { toRegExp } = require('eslint-plugin-vue/dist/utils/regexp').default
+ const { toRegExp } = require('eslint-plugin-vue/dist/utils/regexp')
```
